# Generated by Django 5.2.4 on 2025-07-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_image_post_banner_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_markdown',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='identifier',
            field=models.CharField(default='sss', help_text='Unique identifier for embedding in markdown, e.g. image1', max_length=50),
            preserve_default=False,
        ),
    ]
