# Generated by Django 5.2.4 on 2025-07-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_body_markdown_postimage_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
