# Generated by Django 5.2.4 on 2025-07-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_author_remove_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='identifier',
            field=models.CharField(blank=True, help_text='Unique identifier for embedding in markdown, e.g. image1', max_length=50),
        ),
    ]
